apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL 
          value: http://elasticsearch:9200
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        image: docker.elastic.co/kibana/kibana:6.2.1
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        resources: {}
status: {}

